#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/library?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
#    username: root
#    password: root
#    driver-class-name: com.mysql.jdbc.Driver
#    initialization-mode: always

spring:
    mvc:
      hiddenmethod:
        filter:
          enabled: true
server:
  port: 8083
